import { Wallpaper } from "@/types/wallpaper";

export default function() {
    return (
        <header>
          {/* Hero Container */}
          <div className="mx-auto items-center w-full max-w-7xl px-5 md:px-10 md:pt-16">
            {/* Component */}
            <div className="grid items-center justify-center w-full gap-8 sm:gap-20 lg:grid-cols-1">
              {/* Hero Content */}
              <div className="flex flex-col w-full">
                {/* Hero Title */}
                <h1 className="mb-4 text-primary text-center text-5xl font-bold md:text-6xl">
                  AI genetrate wallpaper
                </h1>
                <p className="mb-6 max-w-lg mx-auto text-center text-sm text-gray-500 sm:text-xl md:mb-10 lg:mb-12">
                  1535 wallpapers generated by AI
                </p>
              </div>
            </div>
          </div>
        </header>
    );
}